### ISSUE TITLE
Can't start docker container

### ISSUE THREAD

**Issue by finishthepint** [erik/hotpot#4]
I'm trying to run this on a local server.  I downloaded the source and built the docker image but when i try to run the container, i get this error: 
`2025-01-08T19:13:48.443578Z  INFO hotpot::web: starting server on http://0.0.0.0:8080
error: invalid digit found in string`

**Comment by erik** [comment]
Can you share more details about the commands you’re running? Sounds like an invalid value is being passed somewhere (and that I should improve the error messaging)

**Comment by juliangaal** [comment]
I am running into the same issue with this docker-compose file

```
services:
  hotpot:
    build: 
      context: Dockerfile
    image: hotpot:latest
    volumes:
      - ./data/:/data/
    ports:
      - 5000:8080
```

Thanks for your help!
